spring:
  datasource:
    url: jdbc:mysql://prod-mysql:3306/concert_reservation?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 1700000
      pool-name: main-pool
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.generate_statistics: false

springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false

logging:
  level:
    org.hibernate.SQL: INFO